import yaml 
import os
import json
import dsp_coregen as coregen
import genexp_parser as gp
from collections import OrderedDict
from typing import List, Dict
import argparse

PS_MEM_WIDTH = 32
DEFAULT_MEM_LATENCY = 2
FPGA_CLK_FREQ = 500.e6
FPROC_MEAS_CHANTYPES = ['rf_mix']

class DSP:
    """
    Class for generating verilog code and associated configuration files from a provided
    dsp_config.yal. Does the following:
        1. Generate dsp_cores.sv:
            a. Instantiates all DSP core blocks, as generated by dsp_coregen.py.
               Each block contains a processor core and associated signal generators 
               (e.g. qubit-drive, readout-drive, readout-demod)
            b. Maps signal outputs to physical ADC/DAC channels according to the provided
               config.
        2. Generate ifdsp.sv -- provides interfaces to registers, memory, and physical
           ADC/DAC channels. 
        3. Generate configs:
            - channel_config.json, used by the compiler to map named channels to 
              physical/firmware sig-gens
            - bram.json, used by the software to map named program/data memory to physical
              addresses.
    """

    def __init__(self, dsp_config: Dict):
        """
        Parameters
        ----------
        dsp_config: Dict
            input from a yaml file
        """
        self.cores: List[coregen.DSPCore] = []
        self.corecounts = OrderedDict(dsp_config['cores'])
        self.config = dsp_config
        self.n_fproc_meas = 0
        for corename, coredict in dsp_config['core_defs'].items():
            sig_gens = []
            rf_mix_used = False #only one rf_mix channer per core
            for i, (name, params) in enumerate(coredict['sig_gens'].items()):
                if params['type'] in FPROC_MEAS_CHANTYPES:
                    self.n_fproc_meas += self.corecounts[corename]
                if 'delay' not in params.keys():
                    params['delay'] = None
                if i > 3:
                    raise Exception('Max 4 sig gens per core!')

                if params['type'] == 'rf':
                    sig_gens.append(coregen.RFSigGen(name, corename, i, params['env_mem_depth'], 
                                                     params['freq_mem_depth'], params['interp_ratio'], 
                                                     delay=params['delay']))
                elif params['type'] == 'dc_offset':
                    sig_gens.append(coregen.DCOffsSigGen(name, corename, i, delay=params['delay']))

                elif params['type'] == 'rf_mix':
                    if rf_mix_used:
                        raise Exception(f'Duplicate mix channels found on core {corename}!')
                    rf_mix_used = True
                    sig_gens.append(coregen.RFMixSigGen(name, corename, i, params['env_mem_depth'], 
                                                        params['freq_mem_depth'], params['acc_mem_depth'], 
                                                        params['interp_ratio'], delay=params['delay']))
                else:
                    raise Exception(f'core type {params["type"]} not found')

            self.cores.append(coregen.DSPCore(corename, coredict['instr_mem_depth'], sig_gens))

        self.ncores = sum(n for n in dsp_config['cores'].values())

        self.coredefs = dsp_config['core_defs']

    def generate_verilog(self, dir_path='gensrc', sim=False):
        core_filenames = []
        for core in self.cores:
            core_filename = os.path.join(dir_path, f'{core.name}_core.sv')
            with open(core_filename, 'w') as f:
                f.write(core.generate_verilog())
            core_filenames.append(core_filename)

        with open(os.path.join(dir_path, 'dsp_cores.sv'), 'w') as f:
            f.write(self._generate_toplevel())

        with open(os.path.join(dir_path, 'ifdsp.sv'), 'w') as f:
            f.write(self._generate_ifdsp())

        with open(os.path.join(dir_path, 'plps_para.vh'), 'w') as f:
            f.write(self._generate_plps_para())

        with open(os.path.join(dir_path, 'bram0.json'), 'w') as f:
            f.write(json.dumps(self.get_bram_dict(), indent=4))

        with open(os.path.join(dir_path, 'channel_config.json'), 'w') as f:
            f.write(json.dumps(self._generate_channel_config(), indent=4))

        with open(os.path.join(dir_path, 'channel_map.txt'), 'w') as f:
            f.write(self._generate_chanmap())
        
        plps_d_path = os.path.join(dir_path, '../' 'plps.d')
        with open(plps_d_path, 'a') as f:
            f.write('\n'.join([os.path.relpath(cf, start=os.path.dirname(plps_d_path)) 
                               for cf in core_filenames]))

        if sim:
            verilog_str, memory_map = self._generate_sim_toplevel()
            with open(os.path.join(dir_path, 'dsp_sim_toplevel.sv'), 'w') as f:
                f.write(verilog_str)
            with open(os.path.join(dir_path, 'sim_memory_map.json'), 'w') as f:
                f.write(json.dumps(memory_map, indent=4))

    def _generate_ifdsp(self):
        verilog_str = \
            f'    interface ifdsp #( \n' \
            f'      `include "plps_para.vh" \n' \
            f'      ,`include "bram_para.vh" \n' \
            f'      ,`include "braminit_para.vh" \n' \
            f'      )(); \n\n' \
            f'      wire clk; \n' \
            f'      wire reset; \n' \
            f'      logic [ADC_AXIS_DATAWIDTH-1:0] adc[0:NADC-1]; \n' \
            f'      logic [DAC_AXIS_DATAWIDTH-1:0] dac[0:NDAC-1]; \n' \
            f'    \n' \
            f'      logic [DACMON_W_DATAWIDTH-1:0] data_dacmon[0:NDACMON-1]; \n' \
            f'      reg [DACMON_W_ADDRWIDTH-1:0] addr_dacmon[0:NDACMON-1]; \n' \
            f'      reg we_dacmon[0:NDACMON-1]; \n' \
            f'     \n' \
            f'      logic [ACQBUF_W_DATAWIDTH-1:0] data_acqbuf[0:NACQ-1]; \n' \
            f'      reg [ACQBUF_W_ADDRWIDTH-1:0] addr_acqbuf[0:NACQ-1]; \n' \
            f'      reg we_acqbuf[0:NACQ-1]; \n' \
            f'     \n' \

        for core in self.cores:
            verilog_str += \
                f'      logic [{core.instr_mem.name.upper()}_R_DATAWIDTH-1:0] data_{core.instr_mem.name}[0:{self.corecounts[core.name]}-1]; \n' \
                f'      reg [{core.instr_mem.name.upper()}_R_ADDRWIDTH-1:0] addr_{core.instr_mem.name}[0:{self.corecounts[core.name]}-1]; \n' \
                f'      reg we_{core.instr_mem.name}[0:{self.corecounts[core.name]}-1]; \n\n' 

            for gen in core.sig_gens:
                for mem in gen.write_mems:
                    verilog_str += \
                        f'      logic [{mem.name.upper()}_W_DATAWIDTH-1:0] data_{mem.name}[0:{self.corecounts[core.name]}-1]; \n' \
                        f'      reg [{mem.name.upper()}_W_ADDRWIDTH-1:0] addr_{mem.name}[0:{self.corecounts[core.name]}-1]; \n' \
                        f'      reg we_{mem.name}[0:{self.corecounts[core.name]}-1]; \n\n' \

                for mem in gen.read_mems:
                    verilog_str += \
                        f'      logic [{mem.name.upper()}_R_DATAWIDTH-1:0] data_{mem.name}[0:{self.corecounts[core.name]}-1]; \n' \
                        f'      reg [{mem.name.upper()}_R_ADDRWIDTH-1:0] addr_{mem.name}[0:{self.corecounts[core.name]}-1]; \n' \
                        f'      reg we_{mem.name}[0:{self.corecounts[core.name]}-1]; \n\n' \

        #todo: remove hardcoded values
        verilog_str += \
            f'      logic stb_start; \n' \
            f'      logic start; \n' \
            f'      logic [31:0] nshot; \n' \
            f'      logic resetacc; \n' \
            f'      logic stb_reset_bram_read; \n' \
            f'      logic lastshotdone; \n' \
            f'      logic [31:0] shotcnt; \n' \
            f'      logic [10:0] addr_accbuf_mon0; \n' \
            f'      logic [10:0] addr_accbuf_mon1; \n' \
            f'      logic [10:0] addr_accbuf_mon2; \n' \
            f'      logic [10:0] addr_accbuf_mon3; \n' \
            f'      (* ram_style = "registers" *) \n' \
            f'      logic [31:0]coef  [0:NDAC-1][0:NDAC-1]; \n' \
            f'     \n' \
            f'     \n' \
            f'      logic acqbufreset; \n' \
            f'      logic dacmonreset; \n' \
            f'      logic [15:0] acqchansel[0:NACQ-1]; \n' \
            f'      logic [15:0] dacmonchansel[0:NACQ-1]; \n' \
            f'      logic [31:0] delayaftertrig; \n' \
            f'      logic [15:0] decimator; \n' \
            f'      logic [15:0] mixbb1sel; \n' \
            f'      logic [15:0] mixbb2sel; \n' \
            f'      logic [4:0] acc_shift; \n' \
            f'      logic [NPROC-1:0] procdone; \n' \
            f'     \n' \
            f'     \n' \
            f'      logic [23:0] test_freq; \n' \
            f'      logic [15:0] test_amp; \n' \
            f'      modport dsp(input clk,reset,acqbufreset,dacmonreset,acqchansel,dacmonchansel,delayaftertrig,decimator \n' \
            f'                  ,input {", ".join([f"data_{core.instr_mem.name}" for core in self.cores])}\n'\
            f'                  ,input {", ".join([f"data_{mem.name}" for core in self.cores for gen in core.sig_gens for mem in gen.read_mems])} \n'\
            f'                  ,input adc \n' \
            f'                  ,input stb_start,start,nshot,resetacc,stb_reset_bram_read \n' \
            f'                  ,input coef,mixbb1sel,mixbb2sel,acc_shift \n' \
            f' \n'\
            f'                  ,output lastshotdone,shotcnt,addr_accbuf_mon0,addr_accbuf_mon1,addr_accbuf_mon2,addr_accbuf_mon3,procdone \n' \
            f'                  ,output dac \n'\
            f'                  ,output {", ".join([f"addr_{core.instr_mem.name}" for core in self.cores])}\n'\
            f'                  ,output {", ".join([f"addr_{mem.name}" for core in self.cores for gen in core.sig_gens for mem in gen.read_mems])} \n'

        write_mems = [mem for core in self.cores for gen in core.sig_gens for mem in gen.write_mems]
        if len(write_mems) > 0:
            verilog_str += \
                f'                  ,output {", ".join([f"addr_{mem.name}" for mem in write_mems])} \n'\
                f'                  ,output {", ".join([f"data_{mem.name}" for mem in write_mems])} \n'\
                f'                  ,output {", ".join([f"we_{mem.name}" for mem in write_mems])} \n'

        verilog_str += \
            f'                  ,output addr_dacmon, data_acqbuf, addr_acqbuf, we_acqbuf, data_dacmon, we_dacmon \n' \
            f'                  ,input test_amp,test_freq \n' \
            f'      ); \n' \
            f' \n'\
            f'      modport cfg(output adc \n' \
            f'                  ,output clk,reset \n' \
            f'                  ,output {", ".join([f"data_{core.instr_mem.name}" for core in self.cores])}\n'\
            f'                  ,output {", ".join([f"data_{mem.name}" for core in self.cores for gen in core.sig_gens for mem in gen.read_mems])} \n'\
            f'                  ,output stb_start,start,nshot,resetacc,stb_reset_bram_read,acqbufreset,dacmonreset,acqchansel,dacmonchansel,delayaftertrig,decimator \n' \
            f'                  ,output coef,mixbb1sel,mixbb2sel,acc_shift \n' \
            f'                  ,input dac \n' \
            f'                  ,input addr_dacmon, data_acqbuf, addr_acqbuf, we_acqbuf, data_dacmon, we_dacmon \n' \
            f'                  ,input {", ".join([f"addr_{core.instr_mem.name}" for core in self.cores])}\n'\
            f'                  ,input {", ".join([f"addr_{mem.name}" for core in self.cores for gen in core.sig_gens for mem in gen.read_mems])} \n'\

        if len(write_mems) > 0:
            verilog_str += \
                f'                  ,input {", ".join([f"addr_{mem.name}" for mem in write_mems])} \n'\
                f'                  ,input {", ".join([f"data_{mem.name}" for mem in write_mems])} \n'\
                f'                  ,input {", ".join([f"we_{mem.name}" for mem in write_mems])} \n'
        verilog_str += \
            f'                  ,input lastshotdone,shotcnt,addr_accbuf_mon0,addr_accbuf_mon1,addr_accbuf_mon2,addr_accbuf_mon3,procdone \n' \
            f'                  ,output test_amp,test_freq \n' \
            f'      ); \n' \
            f'    endinterface \n' 

        return verilog_str

    def _generate_toplevel(self):
        verilog_str = \
            f'// autogenerated by dsp_build.py \n' \
            f'module dsp_cores#( \n' \
            f'    `include "plps_para.vh", \n' \
            f'    `include "bram_para.vh", \n' \
            f'    `include "braminit_para.vh" \n' \
            f'    )(ifdsp.dsp dspif, \n' \
            f'      input reset,  \n' \
            f'      output[NPROC-1:0] procdone,  \n' \
            f'      output[NPROC-1:0] nobusy);  \n\n' 

        # declare fproc
        verilog_str += \
            f'    fproc_iface fproc_if[NPROC-1:0](); \n' 
        if self.n_fproc_meas > 0:
            verilog_str += \
                f'    reg [{self.n_fproc_meas}-1:0] fproc_meas_input; \n' \
                f'    reg [{self.n_fproc_meas}-1:0] fproc_meas_valid; \n' \
                f'    fproc_meas #(.N_CORES(NPROC), .N_MEAS({self.n_fproc_meas})) fproc(.clk(dspif.clk), .reset(reset), .meas(fproc_meas_input), \n' \
                f'      .meas_valid(fproc_meas_valid), .core(fproc_if)); \n\n' \

        # declare input/output signals
        for core in self.cores:
            for gen in core.sig_gens:
                for signal in gen.output_signals:
                    verilog_str += \
                        f'    wire signed [DAC_AXIS_DATAWIDTH-1:0] {signal.global_name}[0:{self.corecounts[core.name]-1}]; \n'\
                        f'    wire signed [DAC_AXIS_DATAWIDTH-1:0] {signal.global_name}_gen[0:{self.corecounts[core.name]-1}]; \n\n'
                    if gen.delay is not None:
                        for i in range(gen.delay):
                            verilog_str += \
                                f'    reg signed [DAC_AXIS_DATAWIDTH-1:0] {signal.global_name}_d{i}[0:{self.corecounts[core.name]}-1]; \n'

                        verilog_str += \
                            f'\n'\
                            f'    always @(posedge dspif.clk) begin \n' \
                            f'        {signal.global_name}_d0 <= {signal.global_name}_gen; \n'

                        for i in range(1, gen.delay):
                            verilog_str += \
                                f'        {signal.global_name}_d{i} <= {signal.global_name}_d{i-1}; \n'

                        verilog_str += \
                            f'    end\n\n' \
                            f'    assign {signal.global_name} = {signal.global_name}_d{gen.delay - 1}; \n\n'

                    else:
                        verilog_str += \
                            f'    assign {signal.global_name} = {signal.global_name}_gen; \n\n'

                for signal in gen.input_signals:
                    verilog_str += \
                        f'    wire signed [ADC_AXIS_DATAWIDTH-1:0] {signal.global_name}[0:{self.corecounts[core.name]}-1]; \n'



        # declare cores
        global_coreind = 0 # global core count, for e.g. FPROC and reset signals
        for core in self.cores:
            for gen in core.sig_gens:
                for port in gen.misc_io_ports:
                    if not port.dspif:
                        portname = port.global_name
                        if port.width > 1:
                            portname = f'[{port.width-1}:0] {portname}'
                        if port.indexed:
                            portname = f'{portname}[0:{self.corecounts[core.name]-1}]'
                        verilog_str += \
                                f'    wire {portname}; \n\n'
            verilog_str += \
                    f'    generate for(genvar i = 0; i < {self.corecounts[core.name]}; i = i + 1) begin: {core.name}\n' 

            decl_body = f'.clk(dspif.clk), .reset(reset), \n' \
                f'                                     .command(dspif.data_{core.instr_mem.name}[i]), \n' \
                f'                                     .cmd_read_addr(dspif.addr_{core.instr_mem.name}[i]), \n' \
                f'                                     .procdone_mon(procdone[{global_coreind} + i]), \n' \
                f'                                     .nobusy_mon(nobusy[{global_coreind} + i]), \n\n' 

            for gen in core.sig_gens:
                for mem in gen.read_mems:
                    decl_body += \
                        f'                                     .data_{mem.name}(dspif.data_{mem.name}[i]), \n' \
                        f'                                     .addr_{mem.name}(dspif.addr_{mem.name}[i]), \n\n' 
                for mem in gen.write_mems:
                    decl_body += \
                        f'                                     .data_{mem.name}(dspif.data_{mem.name}[i]), \n' \
                        f'                                     .addr_{mem.name}(dspif.addr_{mem.name}[i]), \n' \
                        f'                                     .we_{mem.name}(dspif.we_{mem.name}[i]), \n\n' 
                for signal in gen.output_signals:
                    decl_body += \
                        f'                                     .{signal.local_name}({signal.global_name}_gen[i]), \n' 
                for signal in gen.input_signals:
                    decl_body += \
                        f'                                     .{signal.local_name}({signal.global_name}[i]), \n' 
                for port in gen.misc_io_ports:
                    portname = port.global_name
                    if port.indexed:
                        portname = f'{portname}[i]'
                    if port.dspif:
                        portname = f'dspif.{portname}'

                    decl_body += \
                        f'                                     .{port.local_name}({portname}), \n' 

            decl_body += \
                f'                                     .fproc(fproc_if[{global_coreind} + i])' \
                    

            verilog_str += f'        {core.name}_core {core.name}_inst({decl_body});\n' \
                           f'    end\n'\
                           f'    endgenerate\n\n'
            global_coreind += self.corecounts[core.name]

        # map fproc
        fproc_ind = 0

        for core in self.cores:
            for gen in core.sig_gens:
                if isinstance(gen, coregen.RFMixSigGen):
                    verilog_str += \
                    f'    generate for (genvar i = 0; i < {self.corecounts[core.name]}; i = i + 1) begin: fproc_data \n' \
                    f'        always @(posedge dspif.clk) begin \n' \
                    f'            fproc_meas_valid[i + {fproc_ind}] <= {gen.fproc_valid_port.global_name}[i]; \n' \
                    f'            fproc_meas_input[i + {fproc_ind}] <= dspif.data_{gen.write_mems[0].name}[i][63]; //threshold across x (real) axis \n' \
                    f'        end\n'\
                    f'    end\n'\
                    f'    endgenerate\n\n'

                    fproc_ind += self.corecounts[core.name]


        # map output signals
        for blockind, block in enumerate(self.config['dac_outputs']):
            blocktype = list(block.keys())[0]
            body = block[blocktype]
            if blocktype == 'sum':
                corename, genname = body['sig_gens'].split('.')
                if 'range' in body:
                    lower, upper = [int(a) for a in body['range'].split(',')]
                    rangestr = f'[{lower}:{upper-1}]'
                    nitem = upper-lower
                else:
                    rangestr = ''
                    nitem = self.corecounts[corename]

                verilog_str += \
                    f'    slicesum #(.DATAWIDTH(DAC_AXIS_DATAWIDTH),.NITEM({nitem})) \n' \
                    f'        sumelemout_{blockind} (.clk(dspif.clk),.xin({corename}_{genname}_gen{rangestr}),.yin(), \n' \
                    f'            .valid(),.xout(dspif.dac[{body["dac_ind"]}]),.yout()); \n' 
            elif blocktype == 'gen':
                genvar, genrange, dac_inds, rhs_exp = gp.parse_genblock(body)
                verilog_str += \
                        f'    generate \n' \
                        f'      for (genvar splice = 0; splice < 16; splice = splice + 1) begin \n' \
                        f'          for(genvar {genvar} = {genrange[0]}; {genvar} < {genrange[1]}; {genvar} = {genvar} + 1) begin \n' \
                        f'              assign dspif.dac[{dac_inds}][((splice+1)*16)-1:splice*16] = {gp.append_to_operands(rhs_exp, "[((splice+1)*16)-1:splice*16]")}; \n' \
                        f'          end \n' \
                        f'      end \n' \
                        f'    endgenerate \n\n'

        # map input signals
        if 'adc_mix_inputs' in self.config.keys():
            for block in self.config['adc_mix_inputs']:
                blocktype = list(block.keys())[0]
                body = block[blocktype]
                if blocktype == 'sum':
                    pass
                elif blocktype == 'gen':
                    genvar, genrange, lhs_exp, adc_inds = gp.parse_genblock(body)
                    verilog_str += \
                            f'    generate for(genvar {genvar} = {genrange[0]}; {genvar} < {genrange[1]}; {genvar} = {genvar} + 1) begin \n' \
                            f'        assign {lhs_exp} = dspif.adc[{adc_inds}]; \n' \
                            f'    end \n' \
                            f'    endgenerate \n\n'

        verilog_str += 'endmodule'

        return verilog_str

    def _generate_sim_toplevel(self):
        verilog_str = ''
        global_memwrite_ind = 0
        global_memread_ind = 0
        sim_memory_map = {}
        for core in self.cores: 
            for coreind in range(self.corecounts[core.name]):
                verilog_str += \
                        f'    wire wen_{global_memwrite_ind}; \n' \
                        f'    assign wen_{global_memwrite_ind} = mem_write_en & (mem_write_ind == {global_memwrite_ind}); \n' \
                        f'    aligned_ram #(.DIN_WIDTH(32), .N_DIN_TO_DOUT(5), .DOUT_ADDR_WIDTH({core.instr_mem.name.upper()}_R_ADDRWIDTH-1), .READ_LATENCY(2)) \n' \
                        f'    mem_w_{global_memwrite_ind}(.clk(clk), .write_data(mem_write_data), .write_addr(mem_write_addr[{core.instr_mem.name.upper()}_W_ADDRWIDTH-1:0]), \n' \
                        f'        .write_enable(wen_{global_memwrite_ind}), .read_addr(dspif.addr_{core.instr_mem.name}[{coreind}]),  \n' \
                        f'        .read_data(dspif.data_{core.instr_mem.name}[{coreind}])); \n\n' 
                sim_memory_map[f'{core.instr_mem.name}{coreind}'] = global_memwrite_ind
                global_memwrite_ind += 1

                for sig_gen in core.sig_gens:
                    for mem in sig_gen.read_mems:
                        verilog_str += \
                                f'    wire wen_{global_memwrite_ind}; \n' \
                                f'    assign wen_{global_memwrite_ind} = mem_write_en & (mem_write_ind == {global_memwrite_ind}); \n' \
                                f'    aligned_ram #(.DIN_WIDTH(32), .N_DIN_TO_DOUT({mem.name.upper()}_R_DATAWIDTH/32), .DOUT_ADDR_WIDTH({mem.name.upper()}_R_ADDRWIDTH-1), \n'\
                                f'                 .READ_LATENCY(2)) \n' \
                                f'    mem_w_{global_memwrite_ind}(.clk(clk), .write_data(mem_write_data), .write_addr(mem_write_addr[{mem.name.upper()}_W_ADDRWIDTH-1:0]), \n' \
                                f'        .write_enable(wen_{global_memwrite_ind}), .read_addr(dspif.addr_{mem.name}[{coreind}]),  \n' \
                                f'        .read_data(dspif.data_{mem.name}[{coreind}])); \n\n' 
                        sim_memory_map[f'{mem.name}{coreind}'] = global_memwrite_ind
                        global_memwrite_ind += 1
                    for mem in sig_gen.write_mems:
                        verilog_str += \
                                f'    aligned_ram #(.DIN_WIDTH({mem.name.upper()}_W_DATAWIDTH), .N_DIN_TO_DOUT(1), .DOUT_ADDR_WIDTH({mem.name.upper()}_W_ADDRWIDTH), .READ_LATENCY(1)) \n' \
                                f'        mem_r_{global_memread_ind}(.clk(clk), .write_data(dspif.data_{mem.name}[{coreind}]), .write_addr(dspif.addr_{mem.name}[{coreind}]), \n' \
                                f'            .write_enable(dspif.we_{mem.name}[{coreind}]), .read_addr(mem_read_addr[{mem.name.upper()}_W_ADDRWIDTH-1:0]),  \n' \
                                f'                  .read_data(mem_read_data[{global_memread_ind}])); \n' 
                        global_memread_ind += 1

        verilog_header = \
                f'module dsp_sim_toplevel#( \n' \
                f'	`include "plps_para.vh" \n' \
                f'	,`include "bram_para.vh")( \n' \
                f'    input clk, \n' \
                f'    input reset, \n' \
                f'    input stb_start, \n' \
                f'    input[31:0] nshot, \n' \
                f'    input[31:0] mem_write_data, \n' \
                f'    input[15:0] mem_write_ind, \n' \
                f'    input[31:0] mem_write_addr, \n' \
                f'    input mem_write_en, \n' \
                f'    input[12:0] mem_read_addr, \n' \
                f'    input[ADC_AXIS_DATAWIDTH-1:0] adc[0:NADC-1], \n' \
                f'    output[DAC_AXIS_DATAWIDTH-1:0] dac[0:NDAC-1], \n' \
                f'    output[63:0] mem_read_data[0:{global_memread_ind}-1], \n' \
                f'    output[ACQBUF_W_DATAWIDTH-1:0] acq_read_data[0:NADC-1]); \n' \
                f' \n' \
                f'    ifdsp dspif(); \n' \
                f'    assign dac = dspif.dac; \n' \
                f'    assign dspif.adc = adc; \n' \
                f'    assign dspif.clk = clk; \n' \
                f'    assign dspif.reset = reset; \n' \
                f'    assign dspif.resetacc = reset; \n' \
                f'    assign dspif.stb_start = stb_start; \n' \
                f'    assign dspif.nshot = nshot; \n' \
                f'    assign dspif.acc_shift = 15; \n\n' \
                f'    dsp dspmod(.dspif(dspif)); \n\n' \

        verilog_str = verilog_header + verilog_str
        verilog_str += 'endmodule'
        return verilog_str, sim_memory_map


    def get_bram_dict(self):
        bram_dict = {}
        for core in self.cores:
            bram_dict[core.instr_mem.name] = \
                    {'cnt': self.corecounts[core.name], 
                     'cfg':{
                          'Awidth': PS_MEM_WIDTH,
                          'Adepth': core.instr_mem.depth,
                          'Bwidth': core.instr_mem.pl_width,
                          'latency': DEFAULT_MEM_LATENCY,
                          'prefix': core.instr_mem.name.upper(),
                          'access': 'r',
                          'address': None,
                          'ram_style': 'block'
                         }
                     }
            for sig_gen in core.sig_gens:
                for mem in sig_gen.read_mems:
                    bram_dict[mem.name] = \
                        {'cnt': self.corecounts[core.name],
                         'cfg':{
                              'Awidth': PS_MEM_WIDTH,
                              'Adepth': mem.depth,
                              'Bwidth': mem.pl_width,
                              'latency': DEFAULT_MEM_LATENCY,
                              'prefix': mem.name.upper(),
                              'access': 'r',
                              'address': None,
                              'ram_style': 'block'
                             }
                         }

                for mem in sig_gen.write_mems:
                    bram_dict[mem.name] = \
                        {'cnt': self.corecounts[core.name],
                         'cfg':{
                              'Awidth': mem.pl_width,
                              'Adepth': mem.depth,
                              'Bwidth': PS_MEM_WIDTH,
                              'latency': DEFAULT_MEM_LATENCY,
                              'prefix': mem.name.upper(),
                              'access': 'w',
                              'address': None,
                              'ram_style': 'block'
                             }
                         }

            bram_dict['acqbuf'] = {"cnt": 2,
                                   "cfg": {
                                       "Awidth": 64,
                                       "Adepth": 4096,
                                       "Bwidth": 32,
                                       "latency": 2,
                                       "prefix": "ACQBUF",
                                       "access": "w",
                                       "address": None,
                                       "ram_style": "block"}}

            bram_dict['dacmon'] = {"cnt": 4,
                                   "cfg": {
                                       "Awidth": 256,
                                       "Adepth": 512,
                                       "Bwidth": 32,
                                       "latency": 2,
                                       "prefix": "DACMON",
                                       "access": "w",
                                       "address": None,
                                       "ram_style": "block"}}

        return bram_dict

    def _generate_plps_para(self):
        verilog_str = \
            f'parameter DEBUG="true" \n' \
            f',parameter integer LB1_DATAWIDTH=32 \n' \
            f',parameter integer LB1_ADDRWIDTH=10 \n' \
            f',parameter integer LB2_DATAWIDTH=32 \n' \
            f',parameter integer LB2_ADDRWIDTH=10 \n' \
            f',parameter integer LB3_DATAWIDTH=32 \n' \
            f',parameter integer LB3_ADDRWIDTH=20 \n' \
            f',parameter integer LB4_DATAWIDTH=32 \n' \
            f',parameter integer LB4_ADDRWIDTH=20 \n' \
            f',parameter integer DAC_AXIS_DATAWIDTH=256 \n' \
            f',parameter integer ADC_AXIS_DATAWIDTH=64 \n' \
            f',parameter integer BRAMADDRWIDTH=32 \n' \
            f',parameter integer NADC=2 \n' \
            f',parameter integer NPROC={self.ncores} \n' \
            f',parameter integer NDAC=16 \n' \
            f',parameter integer NDACMON=4 \n' \
            f',parameter integer NACQ=2 \n' \
            f',`include "reset_para.vh" \n' 
        return verilog_str

    def _generate_channel_config(self):
        channel_configs = {'fpga_clk_freq': FPGA_CLK_FREQ}
        for core in self.cores:
            for elem_ind, gen in enumerate(core.sig_gens):
                for core_ind in range(self.corecounts[core.name]):
                    channame = f'{core.name}_{core_ind}.{gen.name}'
                    channel_configs[channame] = {
                            'core_ind': core_ind,
                            'elem_ind': elem_ind,
                            'core_name': core.name
                            }
                    if isinstance(gen, coregen.RFSigGen):
                        channel_configs[channame].update({
                            'env_mem_name': f'{core.name}_{gen.name}_env{core_ind}',
                            'freq_mem_name': f'{core.name}_{gen.name}_freq{core_ind}',
                            'elem_params':{
                                'interp_ratio': gen.interp_ratio,
                                'samples_per_clk': gen.samples_per_clk
                                }
                            })
                        if isinstance(gen, coregen.RFMixSigGen):
                            channel_configs[channame].update({
                                'acc_mem_name': f'{core.name}_accbuf{core_ind}',
                                'elem_type': 'rf_mix'
                                })
                        else:
                            channel_configs[channame].update({
                                'elem_type': 'rf'
                                })
                    elif isinstance(gen, coregen.DCOffsSigGen):
                        channel_configs[channame].update({
                            'elem_type': 'dc',
                            'elem_params': {}
                            })
                    else:
                        raise Exception(f'{type(gen)} unsupported!')

        return channel_configs

    def _generate_chanmap(self):
        config_str = 'DACs:\n'
        for blockind, block in enumerate(self.config['dac_outputs']):
            blocktype = list(block.keys())[0]
            body = block[blocktype]
            if blocktype == 'sum':
                corename, genname = body['sig_gens'].split('.')
                if 'range' in body:
                    lower, upper = [int(a) for a in body['range'].split(',')]
                    rangestr = f'[{lower}:{upper-1}]'
                    nitem = upper-lower
                else:
                    rangestr = ''
                    nitem = self.corecounts[corename]

                config_str += \
                        f'    {get_dac_chanmap(body["dac_ind"])} <= {corename}_{genname}{rangestr}\n'


            elif blocktype == 'gen':
                genvar, genrange, dac_inds, rhs_exp = gp.parse_genblock(body)
                for i in range(genrange[0], genrange[1]):
                    config_str += \
                            f'    {get_dac_chanmap(gp.eval_expr(dac_inds, genvar, i))} <= {gp.eval_slices(rhs_exp, genvar, i)}\n'

        config_str += 'ADCs:\n'
        if 'adc_mix_inputs' in self.config:
            for block in self.config['adc_mix_inputs']:
                blocktype = list(block.keys())[0]
                body = block[blocktype]
                if blocktype == 'sum':
                    pass
                elif blocktype == 'gen':
                    genvar, genrange, lhs_exp, adc_inds = gp.parse_genblock(body)
                    for i in range(genrange[0], genrange[1]):
                        config_str += \
                                f'    {gp.eval_slices(lhs_exp, genvar, i)} <= {get_adc_chanmap(gp.eval_expr(adc_inds, genvar, i))}\n'

        return config_str


def get_dac_chanmap(index):
    """
    Converts DAC ind in ifdsp to physical channel; found explicitly in 
    ./zcu216/boardcfg.sv:168. Assumed to be 0 -> 228_0, 1 -> 228_1, etc.
    """
    return f'{228 + index//4}_{index % 4}'

def get_adc_chanmap(index):
    """
    Converts DAC ind in ifdsp to physical channel; found explicitly in 
    ./zcu216/boardcfg.sv:168. Assumed to be 0 -> 228_0, 1 -> 228_1, etc.
    """
    if index == 0:
        return '227_0'
    elif index == 1:
        return '227_2'
    elif index == 2:
        return '226_0'
    elif index == 3:
        return '226_2'
    else:
        raise Exception(f'channel {index} unconnected')
                
if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('build_name', type=str)
    parser.add_argument('config_file', type=str)
    parser.add_argument('--sim', action='store_true')
    args = parser.parse_args()

    build_dir = f'{args.build_name}'
    if not os.path.exists(build_dir):
        os.mkdir(build_dir)
    gensrc_path = os.path.join(build_dir, 'gensrc')
    if not os.path.exists(gensrc_path):
        os.mkdir(gensrc_path)
    with open(args.config_file) as f:
        config = yaml.safe_load(f)

    dsp = DSP(config)
    dsp.generate_verilog(gensrc_path, sim=args.sim)

